// ── FTC Act Section 5 Compliance ─────────────────────────────────────────────
// Unfair or Deceptive Acts or Practices (UDAP)
// The FTC's broad consumer protection authority — applies to all companies.
// Financial apps receive heightened scrutiny.
//
// Core requirement: Don't make false, misleading, or unsubstantiated claims.

export const FTC_CONFIG = {
  version:      '1.0.0',
  lastReviewed: '2026-06-09',
};

// ── Required Disclosures ──────────────────────────────────────────────────────
// These must be prominent — not just buried in Terms of Service
export const REQUIRED_DISCLOSURES = {
  not_financial_advisor: {
    text:      'Zerofi and Nova are not licensed financial advisors. All information is for educational purposes only. Consult a qualified professional before making financial decisions.',
    placement: ['Auth page', 'Nova onboarding', 'Dashboard footer', 'Terms of Service'],
    status:    'implemented',
  },
  not_a_bank: {
    text:      'Zerofi is not a bank. We do not hold, transfer, or insure funds.',
    placement: ['Terms of Service', 'FAQ'],
    status:    'implemented',
  },
  ai_limitations: {
    text:      "Nova's recommendations are generated by AI based on data you provide. They may not account for all factors relevant to your situation.",
    placement: ['Nova sidebar', 'Terms of Service'],
    status:    'policy',
    note:      'Documented in Terms. Add persistent visible disclaimer in Nova sidebar.',
    target:    'Q3 2026',
  },
  data_accuracy: {
    text:      'Financial projections and estimates are based on information you provide and general assumptions. Actual results will vary.',
    placement: ['Tax tab', 'Goals tab', 'Terms of Service'],
    status:    'implemented',
  },
  beta_limitations: {
    text:      'Zerofi is in beta. Features may change and data stability is not guaranteed.',
    placement: ['Beta gate', 'Dashboard banner', 'Terms of Service'],
    status:    'implemented',
  },
};

// ── Marketing Claims Review ───────────────────────────────────────────────────
// Every marketing claim must be truthful and substantiated
export const MARKETING_CLAIMS = {
  'No commissions': {
    claim:   'Zerofi earns no commissions on financial products',
    truthful: true,
    substantiation: 'Business model is subscription-only. No affiliate or referral revenue from financial products.',
  },
  'No data selling': {
    claim:   'We never sell your data',
    truthful: true,
    substantiation: 'Privacy Policy and Terms prohibit data sale. No revenue from data.',
  },
  'End-to-end encrypted': {
    claim:   'Your financial data is encrypted end-to-end',
    truthful: true,
    substantiation: 'AES-256-GCM encryption implemented in src/utils/encrypt.js. Supabase cannot read encrypted values.',
    note:    'Technically: encrypted client-side before upload. "End-to-end" is accurate.',
  },
  'AI-powered advisor': {
    claim:   'Powered by Nova, your AI financial advisor',
    truthful: true,
    substantiation: 'Nova uses rule-based insight engine (novaEngine.js). Future: API-powered AI. Disclosure: not a licensed advisor.',
    note:    'Ensure "advisor" is always qualified with "not a licensed financial advisor" in context.',
  },
};

// ── COPPA 2025 Rule Amendments ────────────────────────────────────────────────
// New requirements effective April 22, 2026
export const COPPA_2025_AMENDMENTS = {
  expanded_personal_info: {
    description: 'Broader definition of personal information now includes biometrics, government IDs',
    applicable:  false,
    note:        'Zerofi does not collect biometrics or government IDs',
    status:      'n/a',
  },
  enhanced_notice: {
    description: 'More detailed notice requirements to parents',
    applicable:  false,
    note:        'Zerofi is 18+ only — COPPA directed-to-children rules do not apply',
    status:      'n/a',
  },
  wisp_required: {
    description: 'Written Information Security Program now explicitly required',
    applicable:  true,
    note:        'WISP.md implemented and maintained',
    status:      'implemented',
    file:        'src/compliance/WISP.md',
  },
  data_retention_limits: {
    description: 'Stricter limits on how long children\'s data can be retained',
    applicable:  false,
    note:        'Zerofi is 18+ only',
    status:      'n/a',
  },
};

// ── ADA / WCAG 2.1 Accessibility ─────────────────────────────────────────────
// Web Content Accessibility Guidelines — courts consistently apply ADA to web/mobile apps
export const ACCESSIBILITY_ROADMAP = {
  current_status: 'not assessed',
  target_level:   'WCAG 2.1 Level AA',
  timeline:       'Mobile app development phase',
  requirements: [
    { criterion: '1.4.3 Contrast Ratio', description: 'Text contrast >= 4.5:1', priority: 'high',   status: 'partial', note: 'Dark theme should be reviewed. Muted text may be insufficient.' },
    { criterion: '2.1.1 Keyboard Access', description: 'All functionality operable via keyboard', priority: 'medium', status: 'roadmap' },
    { criterion: '4.1.2 Name, Role, Value', description: 'All UI components have accessible names', priority: 'high',   status: 'roadmap', note: 'Add ARIA labels to icon buttons and charts' },
    { criterion: '1.1.1 Non-text Content', description: 'Alt text for images and charts', priority: 'medium', status: 'partial', note: 'SVG charts need aria-label attributes' },
    { criterion: '2.4.3 Focus Order', description: 'Logical focus order for keyboard navigation', priority: 'medium', status: 'roadmap' },
    { criterion: '1.4.4 Resize Text',   description: 'Text resizable to 200% without loss', priority: 'low',    status: 'roadmap' },
  ],
};

// ── App Store Compliance ──────────────────────────────────────────────────────
// Required when submitting to Apple App Store and Google Play
export const APP_STORE_COMPLIANCE = {
  status: 'roadmap — mobile app phase',
  apple: {
    privacyNutritionLabels: 'Required — declare all data types collected',
    ageRating:              'Required — 17+ for financial apps',
    termsOfService:         'Must be accessible in app and App Store listing',
    dataUsageDescription:   'Required for each permission requested',
  },
  google: {
    datasSafetySection:     'Required — declare data collection and sharing',
    targetAgeGroup:         'Adults only — restrict to 18+',
    financialServicesPolicy:'Must comply with Google Play financial services policy',
  },
  appStoreAccountabilityActs: {
    states:   ['Utah', 'Texas', 'Arkansas', 'Florida — federal bill pending'],
    requires: 'Age verification, parental controls disclosure, clear ToS/Privacy Policy',
    status:   'Partially satisfied by existing age verification and legal documents',
  },
};

export function getFTCReadiness() {
  const disclosures = Object.values(REQUIRED_DISCLOSURES);
  const impl = disclosures.filter(d => d.status === 'implemented').length;
  const claims = Object.values(MARKETING_CLAIMS).filter(c => c.truthful).length;
  return {
    disclosuresImplemented: impl,
    disclosuresTotal:       disclosures.length,
    claimsVerified:         claims,
    claimsTotal:            Object.keys(MARKETING_CLAIMS).length,
  };
}
